name: Trigger Reusable Output Workflow

on:
  workflow_dispatch:

jobs:
  job1:
    uses: ./.github/workflows/main6_reusable workflow output.yml

  job2:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - run: echo ${{ needs.job1.outputs.firstword }} ${{ needs.job1.outputs.secondword }}
